name: Deploy to CODD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site and migrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          dev: no
          working_dir: site/

      - name: Deploy site
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          ARGS: >-
            -rltzv
            --exclude='.git'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}
          SOURCE: site/
          TARGET: /home/grupo27/Sites

      - name: Transfer database scripts
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          ARGS: >-
            -rltzv
            --exclude='.git'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}
          SOURCE: functions/
          TARGET: /home/grupo27/migrations

      - name: Run migrations to database 27
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_PROD }}
          username: ${{ secrets.REMOTE_USER_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            export PGPASSWORD=${{ secrets.GRUPO27_PASSWORD }}
            psql -h localhost -U grupo27 -d grupo27e3 -f migrations/import_users.sql
            psql -h localhost -U grupo27 -d grupo27e3 -f migrations/update_proposal.sql
            psql -h localhost -U grupo27 -d grupo27e3 -f migrations/patch_serial.sql
